### ISSUE TITLE
Snap to roads fail display trace

### ISSUE THREAD

**Issue by wizjer** [vitalidze/traccar-web#387]
I've encountered a bug in displaying trace when option 'snap to road' is enabled. The behavior can be seen in the video: https://youtu.be/qzy_Nd-pq0Y

**Comment by gsiotas** [comment]
Please check you log for any useful info, before doing this and after and copy paste it here.

**Comment by rafaelolivei** [comment]
Também percebi este erro hoje, realmente está acontecendo..

Em segunda-feira, 7 de dezembro de 2015, gsiotas notifications@github.com
escreveu:

> Please check you log for any useful info, before doing this and after and
> copy paste it here.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/387#issuecomment-162706036
> .

## 

Rafael Oliveira
Analista de Sistemas
(27) 9 9981-4409

**Comment by wizjer** [comment]
In the log has no information about any error (wrapper.log). Beefore and after it look like:

INFO   | jvm 1    | 2015/12/08 00:05:02 | Dec 08, 2015 12:05:02 AM org.traccar.web.server.model.MethodCallLogger invoke
INFO   | jvm 1    | 2015/12/08 00:05:02 | INFO: Login 'jarek'

I'm using mysql database. 

root@dev2:~# java -version
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-1~deb7u1)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)

compiled on:
root@gts:~# javac -version
javac 1.8.0_66
root@gts:~# java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

compilation error log:
[hs_err_pid7941.zip](https://github.com/vitalidze/traccar-web/files/54751/hs_err_pid7941.zip)

**Comment by gsiotas** [comment]
Ok there isn't anything usefull in the logs. I tried in my system and I can confirm that this happening to me as well.

**Comment by wizjer** [comment]
Maybe it depends on the number of points. I noticed that when the route is long it is a problem. At several points no. https://youtu.be/KkFXJgONhiU 
Maybe today will be ok.

**Comment by vitalidze** [comment]
This is an issue with project-osrm, which service is used to find the 'snapped' route. I have submitted a bug there https://github.com/Project-OSRM/osrm-backend/issues/1805

**Comment by vitalidze** [comment]
Issue in Project OSRM was fixed. Now it should work fine.

**Comment by wizjer** [comment]
Ok. Thanks alot.

**Comment by ghost** [comment]
Does that mean, that there is a new release ?  Because, snap 2 road, still don't work for me.

**Comment by vitalidze** [comment]
No, there are no new release. Since the issue was in project OSRM, I thought it will work without any changes in traccar. However, it does not work, something probably changed in response format or something like this.

**Comment by wizjer** [comment]
Tell me one thing please - the error is in the project OSRM - after they repairing the OSRM I have to recompile traccar-dev - ok?. These dependencies are downloaded by Maven? 
Java is a little foreign to me.

**Comment by vitalidze** [comment]
It's not about simple recompilation. This needs to be fixed in code. Project OSRM is not a maven dependency, it is accessed through AJAX request right from the javascript code (the one which is compiled from java code).

**Comment by vitalidze** [comment]
I think it is working fine now. Something was fixed on the server side of the project OSRM. However, they have added some limitation on the number of points. This means if you are trying to use 'snap to roads' for a long track, you should use filter to reduce the number of points, otherwise it will not work.

**Comment by wizjer** [comment]
Thank you for info

**Comment by wizjer** [comment]
I checked. It still does not work. No matter how much is the points. As I have time I can try to run OSRM on localhost. Where in the code is defined host for RM questions?
"This means if you are trying to use 'snap to roads' for a long track, you should use filter to reduce the number of points" - 100 points if I understood - not good :(.

**Comment by vitalidze** [comment]
So, does it work if you have <=100 points in your track? You can check the response from Project OSRM in your web browser (use Chrome Development Tools).

The URL and snapped points loading is defined here: https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/client/controller/ArchiveController.java#L200

**Comment by wizjer** [comment]
if I have > 100  I get  response {"status":400,"status_message":"Too many coodindates"}
if I have < 100 I get response {"status":208,"status_message":"Could not find a matching segment for coordinate 0"}  - dataService in file:[dataService.txt](https://github.com/vitalidze/traccar-web/files/71324/dataService.txt)
You use service match. This service is linked with the trip and the information provided here
[link](https://github.com/Project-OSRM/osrm-backend/commit/78ac3cffde39d5b3003c5efadd033f744fc5c512).
I think correctly?

**Comment by vitalidze** [comment]
Looks like 100 points is the current limitation. I don't think anything can be done here except hosting your own server. As for the 208 I think the match service of project OSRM cannot find a 'snapped' route for your track, meaning most probably there are not enough data or some bug there. Try posting an issue on their tracker with your source data: https://github.com/Project-OSRM/osrm-backend/issues The project is alive, I think they will answer what's wrong with your data.

**Comment by EasywareMX** [comment]
I've changed the OSRM V4 to V5 default, but, every time that server restart, this back to V4. In my db i have matchServiceType OSRM_V5. Why this happens?

**Comment by vitalidze** [comment]
@EasywareMX I think this is a bug. Probably database migration does not work correctly in this case.
