### ISSUE TITLE
no longer displays the google map

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#568]
Hi, some days no longer displays the google map, but other map are working.
Why, what it happened?

![appunti01](https://cloud.githubusercontent.com/assets/16056476/13771442/37501dbe-ea8e-11e5-882b-255df271c90e.png)

**Comment by vitalidze** [comment]
This is a known issue caused by the changes in google maps JavaScript,
which makes open layers 2 library incompatible with it. It was fixed long
time ago in this project by updating the open layers library. Try latest
version of traccar web UI mod and see if it helps.

вторник, 15 марта 2016 г. пользователь Merianna написал:

> Hi, some days no longer displays the google map, but other map are working.
> Why, what it happened?
> 
> [image: appunti01]
> https://cloud.githubusercontent.com/assets/16056476/13771442/37501dbe-ea8e-11e5-882b-255df271c90e.png
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/vitalidze/traccar-web/issues/568

## 

Kind regards, Vitaly Litvak

**Comment by ghost** [comment]
I installed "Minor bugfix release and support of traccar v3.3" but the problem remains...
How do you solve?

  ----- Original Message -----

**Comment by ghost** [comment]
In the log there is this error, why?

2016-03-15 09:21:17  WARN: Unexpected char 60 at (line no=1, column no=1, offset=0) - JsonParsingException (... < QueryBuilder:361 < *:357 < *:409 < DataManager:367 < ConnectionManager:43 < ...)

**Comment by ghost** [comment]
I restart...now work is the google maps you can see ...
Why the application's graphical user interface is different?

**Comment by vitalidze** [comment]
This is because Project switched to the modern theme named "Neptune" couple
of months ago. You can see list of all changes on the official web site
http://traccar.litvak.su .

вторник, 15 марта 2016 г. пользователь Merianna написал:

> I restart...now work is the google maps you can see ...
> Why the application's graphical user interface is different?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/vitalidze/traccar-web/issues/568#issuecomment-196796222

## 

Kind regards, Vitaly Litvak

**Comment by ghost** [comment]
previous version:

![appunti01](https://cloud.githubusercontent.com/assets/16056476/13777593/63ffaf6e-eab1-11e5-8eec-22828b827507.png)

now:

![appunti02](https://cloud.githubusercontent.com/assets/16056476/13777601/6eac483c-eab1-11e5-9e83-3f22763f343f.png)

how can I have the same interface with version 3.3?

**Comment by vitalidze** [comment]
There is no easy way. What's wrong with this theme?

вторник, 15 марта 2016 г. пользователь Merianna написал:

> previous version:
> 
> [image: appunti01]
> https://cloud.githubusercontent.com/assets/16056476/13777593/63ffaf6e-eab1-11e5-8eec-22828b827507.png
> 
> now:
> 
> [image: appunti02]
> https://cloud.githubusercontent.com/assets/16056476/13777601/6eac483c-eab1-11e5-9e83-3f22763f343f.png
> 
> how can I have the same interface with version 3.3?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/vitalidze/traccar-web/issues/568#issuecomment-196797772

## 

Kind regards, Vitaly Litvak

**Comment by ghost** [comment]
nothing wrong ... but the other has better graphics and more intuitive.

  ----- Original Message -----

**Comment by ghost** [comment]
Hi Vitaly  
Can I Have the version 3.3 with Neptune Theme?

  ----- Original Message -----

**Comment by vitalidze** [comment]
Yes, you can. The Neptune theme is the current one used for the latest public available version of web UI Mod.

**Comment by ghost** [comment]
Where can I download it?

Inviato da smartphone Samsung Galaxy.

-------- Messaggio originale --------
Da: Vitaly Litvak notifications@github.com 
Data:15/03/2016  19:54  (GMT+01:00) 
A: vitalidze/traccar-web traccar-web@noreply.github.com 
Cc: Merianna gimanelu@gmail.com 
Oggetto: Re: [traccar-web] no longer displays the google map (#568) 

Yes, you can. The Neptune theme is the current one used for the latest public available version of web UI Mod. —You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub

**Comment by vitalidze** [comment]
I think you already did it. You need to follow instructions from this page: http://traccar.litvak.su/installation.html (as usual)

**Comment by ghost** [comment]
what Is is the name of this theme?

  ----- Original Message -----

**Comment by vitalidze** [comment]
The old theme is named 'blue'.

**Comment by ghost** [comment]
Hi,
Do I just need to change the css in order to have the 3.3 version with the blue theme?

  ----- Original Message -----

**Comment by vitalidze** [comment]
In theory you can change it with CSS. I think it will be quite hard and harder to support it.

The usual way to change theme is to update the GWT module config: https://github.com/vitalidze/traccar-web/blob/dev/src/main/java/org/traccar/web/client/theme/Theme.gwt.xml But simply switching most probably will not work. You can read about GXT themes here: https://docs.sencha.com/gxt-guides/3/ui/theme/Themes.html
